name: Release Drafter
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
permissions:
  contents: read

jobs:
  release-draft:
    permissions:
      pull-requests: write
      contents: write
    uses: coopnorge/github-workflow-release-drafter/.github/workflows/release-drafter-go.yaml@v0
    with:
      ignore-major-changes-for-pattern: '(\S+)\/(v1beta1)\.(\S+)' # Do not replace single quotes with double quotes, single quotes are required to handle the escape characters properly.
