---
on:
  workflow_call:
    inputs:
      environment-matrix-json:
        required: true
        type: string
        description: |
          A json array containing info about environments. Required keys are 'destination-cluster'. That can be api-production
          or api-staging. If do-argocd-diff=true then 'argocd-appname' and 'argocd-tracking-directory' are also required.
          Example:
          [{
              "argocd-appname": "helloworld-api-production-helloworld",
              "argocd-tracking-directory": "kubernetes/kustomize-deployments/production" ,
              "destination-cluster" : "api-production",
            },
            {
              "argocd-appname": "helloworld-api-staging-helloworld",
              "argocd-tracking-directory": "kubernetes/kustomize-deployments/staging" ,
              "destination-cluster" : "api-staging",
          }]
      do-argocd-diff:
        required: false
        default: true
        type: boolean
        description: |
          Boolean to enable argocd diff.
      kubernetes-version:
        required: false
        default: 1.21.14
        type: string
        description: |
          Target kubernetes version. Used for schema validation.
      manifest-generator:
        required: false
        default: kustomize
        type: string
        description: |
          Which tool use to render manifests. Currently supported: kustomize (default), helm and plain
    secrets:
      argocd-api-token:
        required: false
        description: |
          Token to get read only access to argocd. This is a global secret secrets.ARGOCD_API_TOKEN
jobs:
  validate-kubernetes:
    env:
      ARGOCD_DEFAULT_DNS: argocd.internal.coop
      ARGOCD_BIN: ./argocd
      SCHEMA_BASE_URL: https://raw.githubusercontent.com/coopnorge/kubernetes-schemas/main
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJSON(inputs.environment-matrix-json) }}
    # General note, may steps need to be in setup in an OCI. Also some stuff can be migrated to an action.
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3

      - name: 'Set ARGOCD_URL'
        run: |
          if [[ "${{matrix.argocd-dns}}" == "" ]] ; then
            echo Using default dns $ARGOCD_DEFAULT_DNS
            echo "ARGOCD_URL=$ARGOCD_DEFAULT_DNS" >> $GITHUB_ENV
          else
            echo Using overriding dns ${{matrix.argocd-dns}}
            echo "ARGOCD_URL=${{matrix.argocd-dns}}" >> $GITHUB_ENV
          fi
      - name: Install kustomize
        if: ${{ inputs.manifest-generator == 'kustomize' }}
        uses: imranismail/setup-kustomize@v1

      - name: Set kustomize render command
        if: ${{ inputs.manifest-generator == 'kustomize' }}
        run: |
          echo "render_manifest=kustomize build ${{ matrix.argocd-tracking-directory }}" >> $GITHUB_ENV

      - name: Install helm
        if: ${{ inputs.manifest-generator == 'helm' }}
        uses: azure/setup-helm@v3
        with:
          version: v3.9.0

      - name: Set helm render command
        if: ${{ inputs.manifest-generator == 'helm' }}
        run: |
          echo "render_manifest=helm template ${{ matrix.argocd-tracking-directory }}" >> $GITHUB_ENV

      - name: Install yq
        if: ${{ inputs.manifest-generator == 'plain' }}
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O ./yq &&\
          chmod +x ./yq

      - name: Set plain render command
        if: ${{ inputs.manifest-generator == 'plain' }}
        run: |
          echo "render_manifest=./yq ${{ matrix.argocd-tracking-directory }}/*" >> $GITHUB_ENV

      - name: Install kubescore
        if: ${{ matrix.disable-kubescore != true  }}
        run: |
          wget -q -O- https://github.com/zegl/kube-score/releases/download/v1.14.0/kube-score_1.14.0_linux_amd64 > kube-score
          chmod +x kube-score

      - name: Install kubeconform
        run: |
          wget -q -O- https://github.com/yannh/kubeconform/releases/download/v0.4.13/kubeconform-linux-amd64.tar.gz | tar -xzvf - kubeconform

      - name: Install Argo CD Cli
        if: inputs.do-argocd-diff == true
        run: |
          wget -q -O- https://${ARGOCD_URL}/download/argocd-linux-amd64 > ${ARGOCD_BIN}
          chmod +x ${ARGOCD_BIN}

      - name: Install Dyff
        run: |
          wget -q -O- https://github.com/homeport/dyff/releases/download/v1.5.1/dyff_1.5.1_linux_amd64.tar.gz | tar -xzvf - dyff

      - name: Prepare helm manifests
        if: ${{ inputs.manifest-generator == 'helm' }}
        run: |
          helm dep up ${{ matrix.argocd-tracking-directory }}

      - name: Lint helm manifests
        if: ${{ inputs.manifest-generator == 'helm' }}
        run: |
          helm lint ${{ matrix.argocd-tracking-directory }}

      - name: Check kube-score
        if: ${{ matrix.disable-kubescore != true  }}
        run: |
          ${{ env.render_manifest }} \
          | ./kube-score \
            score  -

      - name: Check kube-confrom
        run: |
          ${{ env.render_manifest }} \
            | ./kubeconform \
              -strict \
              -verbose \
              -ignore-missing-schemas \
              -kubernetes-version ${{ inputs.kubernetes-version }} \
              -schema-location default \
              -schema-location ${SCHEMA_BASE_URL}/${{ matrix.destination-cluster }}/'{{ .ResourceKind }}{{ .KindSuffix }}.json'

      - name: Check diff
        if: inputs.do-argocd-diff == true
        id: argocd-diff
        run: |
          set -x
          ${ARGOCD_BIN} \
            --auth-token ${ARGOCD_API_TOKEN:=EMPTY} \
            --grpc-web --server $ARGOCD_URL \
            app get ${{ matrix.argocd-appname}} --refresh
          set +e
          ${ARGOCD_BIN} \
            --auth-token ${ARGOCD_API_TOKEN:=EMPTY} \
            --grpc-web --server $ARGOCD_URL \
            app diff ${{ matrix.argocd-appname}} \
              --local ${{ matrix.argocd-tracking-directory }} > diff.txt ; EXIT=$?
          set -e
          case $EXIT in
            2)
              echo "General code error"
              exit 1
              ;;
            1)
              echo "Found diff"
              ;;
            0)
              echo "No diff found"
              echo "# no diff" >> diff.txt
              ;;
            *)
              echo "Unknown exit code"
              exit 1
              ;;
          esac
          echo "Diff compared to actual state for app **${{ matrix.argocd-appname }}**" > body.txt
          echo >> body.txt
          echo >> body.txt
          echo "\`\`\`yaml" >> body.txt
          cat diff.txt | head -c 64000 >> body.txt
          echo "\`\`\`" >> body.txt

        env:
          ARGOCD_API_TOKEN: ${{ secrets.argocd-api-token }}
          KUBECTL_EXTERNAL_DIFF: "./dyff between --omit-header"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        if: github.event_name == 'pull_request' && inputs.do-argocd-diff == true
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Diff compared to actual state for app **${{ matrix.argocd-appname }}**


      - name: Update comment
        if: github.event_name == 'pull_request' && inputs.do-argocd-diff == true
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-file: body.txt
          reactions: rocket
          edit-mode: replace
