---
on:
  workflow_call:
    inputs:
      do-argocd-diff:
        required: false
        default: true
        type: boolean
        description: |
          Boolean to enable argocd diff.
      docker-compose-file:
        type: string
        default: ./docker-compose.yaml
        required: false
        description: |
          Location of the docker-compose file relative to the root of the repository
      docker-compose-service:
        type: string
        default: kubernetes-devtools
        required: false
        description: |
          The name of the service in the docker-compose file to use for validating terraform
      argocd-server:
        type: string
        default: argocd.internal.coop
        required: false
        description: |
          The dns server of ArgoCD. Defaults to 'argocd.internal.coop'
      validate-target:
        type: string
        default: validate
        required: false
        description: |
          Target to run when running the validate step, defaults to 'validate'


    secrets:
      argocd-api-token:
        required: false
        description: |
          Token to get read only access to argocd. This is a global secret secrets.ARGOCD_API_TOKEN
jobs:
  validate-kubernetes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate
        id: validate
        run: |
          docker compose \
            --file ${GITHUB_WORKSPACE}/${{ inputs.docker-compose-file }} \
            run \
            --rm \
            -e ARGOCD_API_TOKEN=${ARGOCD_API_TOKEN} \
            -e ARGOCD_SERVER=${ARGOCD_SERVER} \
            ${{ inputs.docker-compose-service }} ${{ inputs.validate-target }}
        env:
          ARGOCD_API_TOKEN: ${{ secrets.argocd-api-token }}
          ARGOCD_SERVER: ${{ inputs.argocd-server }}

      - name: Check diff
        if: inputs.do-argocd-diff == true
        id: argocd-diff
        run: |
          echo "ArgoCD Diff" > body.txt
          echo >> body.txt
          echo >> body.txt
          echo "\`\`\`yaml" >> body.txt

          docker compose \
            --file ${GITHUB_WORKSPACE}/${{ inputs.docker-compose-file }} \
            run \
            -e ARGOCD_API_TOKEN=${ARGOCD_API_TOKEN} \
            -e ARGOCD_SERVER=${ARGOCD_SERVER} \
            --rm \
            ${{ inputs.docker-compose-service }} argoCDDiff | head -c 64000 >> body.txt

          echo "\`\`\`" >> body.txt

        env:
          ARGOCD_API_TOKEN: ${{ secrets.argocd-api-token }}
          ARGOCD_SERVER: ${{ inputs.argocd-server }}

      - name: Find Comment
        uses: peter-evans/find-comment@v2
        if: github.event_name == 'pull_request' && inputs.do-argocd-diff == true
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: ArgoCD Diff

      - name: Update comment
        if: github.event_name == 'pull_request' && inputs.do-argocd-diff == true
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body-path: body.txt
          reactions: rocket
          edit-mode: replace
